pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        AWS_DEFAULT_REGION = "${AWS_REGION}"
        S3_BUCKET_NAME = 'ninhnh-vti-bucket-static-web'
    }

    stages {
        stage('Check User') {
            steps {
                sh 'whoami'
            }
        }

        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/ninhdangcap123/Final_Project_DevOps.git', branch: 'main'
            }
        }

        stage('Check AWS CLI') {
            steps {
                sh 'echo $PATH'
                sh 'aws --version'
            }
        }

        stage('Get S3 Website URL') {
            steps {
                script {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials']]) {
                        def websiteConfig = sh(
                            script: "aws s3api get-bucket-website --bucket ${S3_BUCKET_NAME} --region ${AWS_REGION} --output json",
                            returnStdout: true
                        ).trim()
                        
                        if (websiteConfig) {
                            def websiteUrl = "http://${S3_BUCKET_NAME}.s3-website-${AWS_REGION}.amazonaws.com"
                            env.S3_WEBSITE_URL = websiteUrl
                            echo "S3 Website URL: ${env.S3_WEBSITE_URL}"
                        } else {
                            error("No website configuration found for bucket ${S3_BUCKET_NAME}")
                        }
                    }
                }
            }
        }

        stage('Deploy to S3') {
            steps {
                script {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials']]) {
                        sh '''
                        aws s3 sync . s3://ninhnh-vti-bucket-static-web --delete --region us-east-1 --exclude "*" --include "*.html"
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment to S3 was successful!'
            echo "The static site is available at: ${env.S3_WEBSITE_URL}"
        }
        failure {
            echo 'Deployment to S3 failed.'
        }
    }
}
