apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: 084375555299.dkr.ecr.us-east-1.amazonaws.com/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: terraform-20241024033946277900000002.cfwoy6guyqmd.us-east-1.rds.amazonaws.com
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
